// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SysPedido.Infrastructure.Data;

#nullable disable

namespace SysPedido.Infrastructure.Migrations
{
    [DbContext(typeof(SysPedidoDbContext))]
    partial class SysPedidoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SysPedido.Domain.Entities.CamposMonedaExtranjera", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(30)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("ConsecutivoCompania");

                    b.Property<decimal>("MePrecioConIva")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MePrecioSinIva")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo", "EmpresaId");

                    b.ToTable("CamposMonedaExtranjera", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SysPedido.Domain.Entities.Cliente", b =>
                {
                    b.Property<int>("Consecutivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Consecutivo"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CodigoVendedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ConsecutivoVendedor")
                        .HasColumnType("int");

                    b.Property<string>("Contacto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("ConsecutivoCompania");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(160)");

                    b.Property<string>("NumeroRIF")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZonaPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Consecutivo");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.ToTable("Cliente", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SysPedido.Domain.Entities.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("RIF")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Empresa", "PedidoApp");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Nombre = "Empresa 4 - SAWDB",
                            RIF = "J-4444444"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Empresa B - SAWDB",
                            RIF = "J-2222222"
                        });
                });

            modelBuilder.Entity("SysPedido.Domain.Entities.Pedido", b =>
                {
                    b.Property<string>("Numero")
                        .HasColumnType("varchar(11)");

                    b.Property<int?>("ClienteConsecutivo")
                        .HasColumnType("int");

                    b.Property<string>("CodigoCliente")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CodigoMoneda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodigoVendedor")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<int>("ConsecutivoVendedor")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitud")
                        .HasColumnType("float");

                    b.Property<double>("Longitud")
                        .HasColumnType("float");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VendedorConsecutivo")
                        .HasColumnType("int");

                    b.HasKey("Numero");

                    b.HasIndex("ClienteConsecutivo");

                    b.HasIndex("CodigoCliente");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("VendedorConsecutivo");

                    b.HasIndex("CodigoVendedor", "ConsecutivoVendedor");

                    b.ToTable("Pedido", "PedidoApp");
                });

            modelBuilder.Entity("SysPedido.Domain.Entities.Producto", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("varchar(30)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("ConsecutivoCompania");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<decimal>("Existencia")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Codigo", "EmpresaId");

                    b.HasIndex("EmpresaId");

                    b.ToTable("ArticuloInventario", "dbo", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SysPedido.Domain.Entities.RenglonPedido", b =>
                {
                    b.Property<string>("NumeroCotizacion")
                        .HasColumnType("varchar(11)");

                    b.Property<int>("ConsecutivoRenglon")
                        .HasColumnType("int");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CodigoArticulo")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioConIVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecioSinIVA")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRenglon")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("NumeroCotizacion", "ConsecutivoRenglon");

                    b.HasIndex("CodigoArticulo", "EmpresaId");

                    b.ToTable("RenglonPedido", "PedidoApp");
                });

            modelBuilder.Entity("SysPedido.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Usuario", "PedidoApp");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EmpresaId = 4,
                            PasswordHash = "$2a$11$1A47p9DojqvUa2Px6tUNbu0142TS723j1MwewEgLYpVI4SvwpvBSi",
                            Rol = "Admin",
                            Username = "admin"
                        },
                        new
                        {
                            Id = 2,
                            EmpresaId = 2,
                            PasswordHash = "$2a$11$1A47p9DojqvUa2Px6tUNbu0142TS723j1MwewEgLYpVI4SvwpvBSi",
                            Rol = "Vendedor",
                            Username = "ventas"
                        });
                });

            modelBuilder.Entity("SysPedido.Domain.Entities.Vendedor", b =>
                {
                    b.Property<int>("Consecutivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Consecutivo"));

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int")
                        .HasColumnName("ConsecutivoCompania");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.Property<string>("RIF")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusVendedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZonaPostal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Consecutivo");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Vendedor", "Adm", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("SysPedido.Domain.Entities.CamposMonedaExtranjera", b =>
                {
                    b.HasOne("SysPedido.Domain.Entities.Producto", null)
                        .WithOne("CamposMonedaExtranjera")
                        .HasForeignKey("SysPedido.Domain.Entities.CamposMonedaExtranjera", "Codigo", "EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SysPedido.Domain.Entities.Cliente", b =>
                {
                    b.HasOne("SysPedido.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SysPedido.Domain.Entities.Pedido", b =>
                {
                    b.HasOne("SysPedido.Domain.Entities.Cliente", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("ClienteConsecutivo");

                    b.HasOne("SysPedido.Domain.Entities.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("CodigoCliente")
                        .HasPrincipalKey("Codigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SysPedido.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SysPedido.Domain.Entities.Vendedor", null)
                        .WithMany("Pedidos")
                        .HasForeignKey("VendedorConsecutivo");

                    b.HasOne("SysPedido.Domain.Entities.Vendedor", "Vendedor")
                        .WithMany()
                        .HasForeignKey("CodigoVendedor", "ConsecutivoVendedor")
                        .HasPrincipalKey("Codigo", "Consecutivo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");

                    b.Navigation("Vendedor");
                });

            modelBuilder.Entity("SysPedido.Domain.Entities.Producto", b =>
                {
                    b.HasOne("SysPedido.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SysPedido.Domain.Entities.RenglonPedido", b =>
                {
                    b.HasOne("SysPedido.Domain.Entities.Pedido", "Pedido")
                        .WithMany("Renglones")
                        .HasForeignKey("NumeroCotizacion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SysPedido.Domain.Entities.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("CodigoArticulo", "EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("SysPedido.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SysPedido.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SysPedido.Domain.Entities.Vendedor", b =>
                {
                    b.HasOne("SysPedido.Domain.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("SysPedido.Domain.Entities.Cliente", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("SysPedido.Domain.Entities.Pedido", b =>
                {
                    b.Navigation("Renglones");
                });

            modelBuilder.Entity("SysPedido.Domain.Entities.Producto", b =>
                {
                    b.Navigation("CamposMonedaExtranjera");
                });

            modelBuilder.Entity("SysPedido.Domain.Entities.Vendedor", b =>
                {
                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
